# Generated by Django 3.0.6 on 2020-05-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название репозитория')),
                ('link', models.CharField(max_length=75, verbose_name='Ссылка на репозиторий')),
                ('description', models.TextField(default='', max_length=2500, verbose_name='Описание репозитория')),
                ('number_of_commits', models.PositiveSmallIntegerField(default=0, verbose_name='Количество коммитов')),
            ],
        ),
    ]
