# Generated by Django 3.0.6 on 2020-05-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name': 'Репозиторий', 'verbose_name_plural': 'Репозитории'},
        ),
    ]
