# Generated by Django 3.0.6 on 2020-05-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_commits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commits',
            options={'verbose_name': 'Коммит', 'verbose_name_plural': 'Коммиты'},
        ),
    ]
