# Generated by Django 3.0.6 on 2020-06-18 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0007_auto_20200529_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commits',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
