version: '3.3'

services:

  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
    - postgres:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"

  web:
    build: ./backend
    command: bash -c "while !</dev/tcp/portfolioproject_db_1/5432; do sleep 3; done; python /app/backend/portfolio/manage.py migrate --noinput && python /app/backend/portfolio/manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: ./backend
    command: celery -A portfolio worker -l info
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
      - redis

  celery-beat:
    build: ./backend
    command: celery -A portfolio beat -l info
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
      - redis

volumes:
  postgres:
