# Generated by Django 3.0.6 on 2020-05-26 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название проекта')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание проекта')),
                ('link', models.CharField(max_length=100, verbose_name='Ссылка на проект')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Скриншот проекта')),
                ('image_description', models.CharField(max_length=100, verbose_name='Описание скриншота')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='projects.Project')),
            ],
        ),
    ]
