# Generated by Django 3.0.6 on 2020-05-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинки'},
        ),
    ]
