# Generated by Django 3.0.6 on 2020-05-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200528_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/', verbose_name='Скриншот проекта'),
        ),
    ]
